UserStats = function() {
	/**
	 * Update the stats display with new data
	 * @param {Object} data Complete stats data, as generated by swg_userstats helper
	 */
	document.addEvent("attendanceChange", function(data) {
		var stats = data.stats;
		var periods = new Array("month", "3month", "year", "alltime");
		
		// TODO: Message for IE<8 users to refresh the page
		periods.forEach(function(period)
		{
			// Replace data for this period
			document.getElementById("stat_walks_"+period).innerHTML = stats.walks[period].count+(stats.walks[period].count > 0 ? " ("+stats.walks[period].sum_distance+")" : "");
			document.getElementById("stat_daywalks_"+period).innerHTML = stats.daywalks[period].count+(stats.daywalks[period].count > 0 ? " ("+stats.daywalks[period].sum_distance+")" : "");
			document.getElementById("stat_avgwalk_"+period).innerHTML = stats.walks[period].mean_distance;
			document.getElementById("stat_avgdaywalk_"+period).innerHTML = stats.daywalks[period].mean_distance;
			document.getElementById("stat_walksled_"+period).innerHTML = stats.led[period].count+(stats.led[period].count > 0 ? " ("+stats.led[period].sum_distance+")" : "");
			
			document.getElementById("stat_socials_"+period).innerHTML = stats.socials[period].count;
			document.getElementById("stat_weekends_"+period).innerHTML = stats.weekends[period].count;
		}, this);
	});
};

UserStats();